name: On Check Suite

on:
  check_suite:
    types: [completed]

jobs:
  on-check-suite:
    name: run-on-check-suite
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
    
