name: On Repository Dispatch

on:
  # https://docs.github.com/pt/rest/repos/repos?apiVersion=2022-11-28#create-a-repository-dispatch-event
  repository_dispatch:

jobs:
  on-repository-dispatch:
    name: run-on-repository-dispatch
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
