name: On Workflow Call

on:
  workflow_call:
    inputs:
      test_value:
        description: Any test value
        type: string
        required: false

jobs:
  on-workflow-call:
    name: run-on-workflow-call
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  dump-inputs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@v6
      with:
        test_value: ${{ inputs.test_value }}
        script: |
          github.log.info('test_value: ' + core.getInput('test_value'))
