name: On Workflow Run

on:
  workflow_run:
    workflows: [ On PR ]

jobs:
  on-workflow-run:
    name: run-on-workflow-run
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

  on-workflow-call:
    uses: pedrox-hs/gh-actions-playground/.github/workflows/onworkflowcall.yml@main
    with:
      test_value: ${{ toJson(github.event.workflow_run.pull_requests) }}
