name: On Workflow Run

on:
  workflow_run:
    workflows: [ On Push ]

jobs:
  on-workflow-run:
    name: run-on-workflow-run
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
