name: On Workflow Call

on:
  workflow_call:
    inputs:
      test_value:
        description: Any test value
        type: string
        required: false

jobs:
  on-workflow-call:
    name: run-on-workflow-call
    runs-on: ubuntu-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"
